name: Matrix with strategy.fail-fast is False
on: workflow_dispatch

jobs:
 matrix-jobs:
  runs-on: ${{matrix.os}}
  strategy:  
    fail-fast: false 
# Here java-version 20 is not available, jobs of Java setup in ubuntu and windows will be 
# discarded but other jobs with java-version 17 will be executed as fail-fast is false
    matrix:
     os:  
      - ubuntu-latest
      - windows-latest
     java-version: [17, 20]
  steps:
   - name: Setup Java JDK
     uses: actions/setup-java@v3.14.1
     with:
      java-version: ${{matrix.java-version}}
      distribution: microsoft
