name: Matrix_With_Index_WF
on: workflow_dispatch
jobs:
 matrix-jobs:
  runs-on: ${{matrix.os}}
  strategy:
    fail-fast: false
    matrix:
     include:
     - index: 0       
       os:  ubuntu-latest
       #java: 17
     - index: 1       
       os:  ubuntu-latest
       #java: 21
     java-version: [17, 21] 
       
  steps:
   - name: Setup Java JDK
     uses: actions/setup-java@v3.14.1
     with:
      java-version: ${{matrix.java-version}}
      distribution: microsoft
