name: Node Js Setup Workflow

on:
 workflow_dispatch
jobs:
 node-js:
  runs-on: ubuntu-latest
  steps:
   - name: Setup Node.js environment
     uses: actions/setup-node@v4.2.0
     with:
       node-version: 22
   - run: node -v 
