name: Reusable Workflow
on:
  workflow_call:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Run Reuseable Build Step
        run: echo 'This reusable workflow can be called by call_reusable_wf....'
